### ISSUE TITLE
won't build on Windows 10 Pro running 32-bit Ada

### ISSUE THREAD

**Issue by byronka** [AdaDoom3/AdaDoom3#33]
c:\gnat\2017\bin\gcc.exe -c -x ada -gnatA -gnatE -gnatW8 -O0 -gnato -gnatf -g -m64 -gnatec=C:\Users\byron\AppData\Local\Temp\GNAT-TEMP-000003.TMP -gnatem=C:\Users\byron\AppData\Local\Temp\GNAT-TEMP-000004.TMP C:\cygwin64\home\byron\dev\AdaDoom3\Engine\main.adb
gnat1.exe: sorry, unimplemented: 64-bit mode not compiled in

   compilation of main.adb failed

gprbuild: *** compilation phase failed

**Comment by MichaelAllenHardeman** [comment]
The GPL (community) version of GPS does not come with x64 bit compiler; for some reason that's only available on linux. The default options for this project try to compile the x64 bit version. You can change the Scenario varibles in GPS, run "gnatmake -P neo.gpr -XBitsize=32", or edit neo.gpr to change the BIT_SIZE constant.

**Comment by MichaelAllenHardeman** [comment]
Or you can pony up the big bucks to get the super deluxe pro edition of GPS from adacore

**Comment by byronka** [comment]
Ok.  Might be worth a brief mention in the README.
